### ISSUE TITLE
Is Error Handling included?

### ISSUE THREAD

**Issue by lbrenman** [FranciscoP/drive-db#1]
Maybe i missed it, but how do i know if a call results in an error? For example, if you call drive.update() with an invalid google sheet id?

**Comment by FranciscoP** [comment]
Excelent question. There are few things that come into mind:
- `.update(id)` makes sure that you have an id or it throws an error. The inner code looks like this:

        if (!this.id)
          throw 'Need a google drive url to update file';

- If there was an error given by the request, it gets logged, but nothing else is done from our side. This is the code right now:

        if (error) {
          console.log(error);
          return false;
          }

- You can check the data after update to make sure it has loaded correctly. To do this, use the `drive.after` function (a callback). You can write something along these lines:

        drive.after = function(data){
          if (data.length) {
            console.log("It worked!");
            }
          return data;
          }
        drive.update("YOUR-SPREADSHEET-ID");

Do you think the situation could be improved? How would you prefer to handle a wrong id?

**Comment by lbrenman** [comment]
i think the .update() should take a success and error callback so i can know if there is an error and let the user know that the id is either incorrect or there was an error retrieving the data.

For example:

drive.update("1BfDC-ryuqahvAVKFpu21KytkBWsFDSV4clNex4F1AXc", function(err, data){
  if (err) {
      console.log('error = '+err);
      return;
  } else {
      console.log("There are " + data.length + " rows");
      return data;
  }
});


So, just to be clear, when the id is not null but still incorrect, i would like to be able to detect this and let the user know.

**Comment by FranciscoP** [comment]
From your last comment and [a tweet](https://twitter.com/FPresencia/status/561550605895077888) I see that I didn't make it clear in the documentation at all, my apologies. I will try to explain how it is intended to work:

When a user requests a page, `drive.load()` should be called. This opens up a local file with the data that is either `db.json` or whichever name you put inside `load()`. No requests to google spreadsheets is made so no option for errors here.

Whenever you want, you can call `drive.update(id)`. This will update the local file with the remote data from the spreadsheet. This is done independently from the `.load()` function due to the long time it takes to retrieve the remote file. For this reason, it isn't expected to get `.update()` in the path of sending the response to the user, so you cannot *let users know* if a request failed since there's no really a user and the data is always there (although it might be outdated).

So you basically never need to tell the user "couldn't retrieve remote file". However, you might want to issue a warning in the case that it is outdated. Right now you can do something along these lines:

    var drive = require('drive-db').load();
    var status = "";
    // Note: drive.info.updated will be changed for drive.updated in the close future
    if (drive.info.updated + 1 * 24 * 3600 * 1000 < new Date().getTime()) {
      status = "The data hasn't been updated in the last 24 hours";
      }
    res.render("whatever", status);

Looking ahead, this is a valid concern and it should be addressed. The id might be wrong or Drive might be unavailable. This should be stored in the `.update()` phase and to be available in the `.load()` one. Setting up a `drive.error` seems like the best option. Also, in case you want to deal with the data on the spot, an argument with `error` could be passed to the callback on `update()` as you suggest. However this won't affect the user.

**Comment by lbrenman** [comment]
Thanks. This helps.

However, my main concern is when the id might be wrong or Drive might be unavailable (especially on first fetch). That is when i would like to notify the user that data is unavailable.

So, i look forward to the drive.error option you mention above :)


Also, am i correct in assuming that this is read only from goggle drive? Can data be written to google drive sheet? If not, i can submit a feature request (and take it out of this thread).

**Comment by FranciscoP** [comment]
If it's for that reason, I recommend simply doing:

     if (!drive.data.length)
      res.render('error', 'There is no data yet!');

About writing to google drive, AFAIK this requires a developer key and, for the uses and scope of this library, this would not be implemented. However please open it and I'll investigate if you really need the key.

**Comment by FranciscoP** [comment]
Updated, now the response status should be stored within `drive.code` and the error, if any, is stored in `drive.error`. The next successful `update()` will remove the error.
