### ISSUE TITLE
Write access

### ISSUE THREAD

**Issue by DaleMitchell** [franciscop/drive-db#10]
Is there a way to write to the spreadsheet on Google Drive?

**Comment by coppolaemilio** [comment]
As far as I know this is read-only. If you want to write/modify data from your backend you will have to use google's API and code that logic within your app.

**Comment by franciscop** [comment]
No, this library is sacrificing this functionality to keep it dead simple. Write access would need Google API keys, which would mean everyone using this would have to go through the long and tedious process instead of the "File => Publish to the web".

However, depending on your situation and if you want to accept user's input, you can create a Google Form, link it to a spreadsheet and use that with this library. I am doing that [in this project for instance](https://web-app.store/) (click on "Publish App"). If you do this make sure to sanitize the data :wink:

**Comment by DaleMitchell** [comment]
Write access is still very useful. If things are meant to stay simple, why not have simple write access?

**Comment by franciscop** [comment]
Because there is no place to write. Google's "simple" spreadsheet API is a read-only JSON from the spreadsheet, you cannot make any request without credentials to edit it.
