### ISSUE TITLE
Add .onfetch() to only transform the data once

### ISSUE THREAD

**Issue by franciscop-sc** [franciscop/drive-db#12]
onload() is not that useful because it's the same as:

```js
drive(sheet).then(onload);
```

It also executes on each load:

```js
const onload = data => {
  console.log('good');
  return data;
};
drive({ sheet, onload });
// 'good'
drive({ sheet, onload });
// 'good'
```

Instead, add an `onfetch()` option that is called only when new data is needed, so that an expensive operation can be cached:

```js
const onfetch = data => {
  console.log('good');
  return data;
};
drive({ sheet, onfetch });
// 'good'
drive({ sheet, onfetch });
// [no output because it's cached]
```

**Comment by franciscop** [comment]
`onfetch()` is not possible since there's a global cache, so two different instances only fetch the data once so there's no clear way of specifying which one of the instance's `onfetch()` to use.

An option could be to do: `fetch() -> onfetch() -> cache in different places` but I'm not sure that's useful.
