### ISSUE TITLE
Error while retrieving data

### ISSUE THREAD

**Issue by HariSankaranarayanan** [franciscop/drive-db#13]
I have got the below error when I tried to retrieve data from google sheets used in my team, which only my team has access to it. Is there any way to overcome that?
Error: Error 302 retrieving https://spreadsheets.google.com/feeds/list/{id}/default/public/values?alt=json

**Comment by franciscop** [comment]
The sheet needs to be made public by "publish to the web" (see README), did you make it public?

**Comment by HariSankaranarayanan** [comment]
It contains some sensitive info, so I presume publishing it to web will make the content available to everyone, is there any workaround for that.

**Comment by franciscop** [comment]
Not really, since no OAuth is needed per-design, then the only way of reading it is by having it public. A low-security (it does NOT replace real security, so sensitive data should still not be included) would be to create a Node.js bridge that hides the actual URL and filters only the needed fields:

Frontend => Node.js App => Sheets

```js
// With express
router.get('/data', async (req, res) => {
  try {
    const data = await drive('abc-def');
    res.json(data.filter(row => ({ abc: row.abc }));
  } catch (error) {
    next(error);
  }
});
```
