### ISSUE TITLE
Access other sheets other than main sheet in worksheet

### ISSUE THREAD

**Issue by DaleMitchell** [franciscop/drive-db#9]
For example, this spreadsheet (https://docs.google.com/spreadsheets/d/1be8mGe-7cA16eylDQijJI7tm_3s7pUdKZSdfJetOt3Q/edit#gid=1349304856) has multiple sheets and I would like to know how to include the sheets for access.

One thing I have noticed is that the URL changes when accessing a different sheet, i.e. https://docs.google.com/spreadsheets/d/1be8mGe-7cA16eylDQijJI7tm_3s7pUdKZSdfJetOt3Q/edit#gid=726470586 is a different sheet from the same spreadsheet that was linked in the first paragraph above.

**Comment by franciscop** [comment]
It *is* supported, just I never documented it because I thought it was very difficult to do. If you look [at this part of the code](https://github.com/franciscop/drive-db/blob/master/index.js#L17) you'll see there's an extra option that is not documented, the `tab`:

```js
  // Load the correct defaults
  const drive = Object.assign({}, {
    sheet: '',
    local: 'db.json',
    cache: 3600,
    onload: d => d,
    tab: 'default',  // od6
    data: []
}, options);
```

It defaults to `default`, which is the first tab. [Look at this thread on StackOverflow](https://stackoverflow.com/q/24531351/938236), both answers are highly relevant. Now I am not sure whether if you just say `tab: '2'` in your options it will work, but I highly recommend trying it. **Please let me know whether or not it works**. Thanks! :heart:

**Comment by franciscop** [comment]
Thanks @byteshiva! I also missed the :+1: from DaleMitchell, which I'll interpret as "It worked!", so I'm closing this issue.

**Comment by byteshiva** [comment]
Now I've another question, how about access multiple tabs simultaneously. I mean is there any ways to pass an array of tab elements to options object.

**Comment by byteshiva** [comment]
I think this issue(https://github.com/franciscop/drive-db/issues/4) answers my above question,  Thanks

**Comment by franciscop** [comment]
Please open another issue for these kind of questions in the future, it's easy to miss comments on close issues.

You would have to create an instance per tab:

```js
const Drive = require('drive-db');
const options = { sheet: id, cache: 30 };
const tab1 = Drive({ ...options, local: 'tab1.json' });
const tab2 = Drive({ ...options, tab: '2', local: 'tab2.json' });
```

Note: in this example, `Drive` is the factory/class while in the docs `drive` refers to an instance. That is why in this example I write it with capital letter.

**Comment by franciscop** [comment]
Yes, issue #4 seems to be the same thing I wrote above, but here written with more modern JS syntax.

**Comment by franciscop** [comment]
Actually no, issue #4 is using the old callback syntax and it won't work anymore. load() does not accept a callback anymore, now load() will return a promise.
